name: Build and upload artifact

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-multilib g++-multilib
        rustup toolchain install nightly
        rustup target add --toolchain nightly i586-unknown-linux-gnu
        rustup override set nightly
        cargo b --release --target i586-unknown-linux-gnu
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: target/i586-unknown-linux-gnu/release/libaudio_3dxp.so
