name: Build and upload artifact

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        target: i586-unknown-linux-gnu
    - name: Build
      run: cargo build --release --all-features
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: target/i586-unknown-linux-gnu/release/libaudio_3dxp.so
